name: cwcgl

options:
  bundleIdPrefix: io.github.takeiteasy
  createIntermediateGroups: true
  deploymentTarget:
    macOS: "12.0"

settings:
  GCC_C_LANGUAGE_STANDARD: c11

targets:
  cwcgl:
    type: tool
    platform: macOS
    sources:
        - path: tools/
          type: folder
        - path: build/
          type: folder
        - path: project.yml
          type: folder
        - path: README.md
          type: folder
        - path: Makefile
          type: folder
        - path: src/
          excludes:
            - "backends/"
        - path: src/backends
          type: folder
    dependencies:
        - sdk: Cocoa.framework
    settings:
        HEADER_SEARCH_PATHS: [$(PROJECT_DIR)/src]
        OTHER_CFLAGS: [-DCWCGL_VERSION=2000 -DGL_SILENCE_DEPRECATION]
