name: glWindow

options:
  bundleIdPrefix: io.github.takeiteasy
  createIntermediateGroups: true
  deploymentTarget:
    macOS: "12.0"

settings:
  GCC_C_LANGUAGE_STANDARD: c11

targets:
  glWindow:
    type: application
    platform: macOS
    info:
      path: Info.plist
    sources:
        - path: src
        - path: glWindow.h
        - path: tools/test.c
    dependencies:
        - sdk: Cocoa.framework
    settings:
        HEADER_SEARCH_PATHS: [$(PROJECT_DIR)/src, $(PROJECT_DIR)/]
        OTHER_CFLAGS: [-DGL_SILENCE_DEPRECATION]
