# Generate fungl.h+fungl.c

$stdout.reopen("fungl.h", "w")

puts <<HEADER
/* fungl.h -- https://github.com/takeiteasy/fungl

 Generated by https://github.com/takeiteasy/fungl/tools/fungl.rb
 
 The MIT License (MIT)

 Copyright (c) 2022 George Watson

 Permission is hereby granted, free of charge, to any person
 obtaining a copy of this software and associated documentation
 files (the "Software"), to deal in the Software without restriction,
 including without limitation the rights to use, copy, modify, merge,
 publish, distribute, sublicense, and/or sell copies of the Software,
 and to permit persons to whom the Software is furnished to do so,
 subject to the following conditions:

 The above copyright notice and this permission notice shall be
 included in all copies or substantial portions of the Software.

 THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
 EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
 MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
 IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY
 CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT,
 TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE
 SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE. */

#ifndef fungl_h
#define fungl_h
#ifdef __cplusplus
extern "C" {
#endif

/*!
* @header fungl
* @copyright George Watson
*/
HEADER
    
def importHeader(path)
    skip = true
    File.readlines(path).each do |line|
        if skip
            skip = false if line =~ /^#endif/
        else
            if line =~ /^#ifdef __cplusplus/
                break
            else
                puts line
            end
        end
    end
end

importHeader("src/glLoader.h")
importHeader("src/glWindow.h")

puts <<HEADER
#ifdef __cplusplus
}
#endif
#endif // fungl_h
HEADER
    
$stdout.reopen("fungl.c", "w")
    
puts <<HEADER
/* fungl.c -- https://github.com/takeiteasy/fungl

Generated by https://github.com/takeiteasy/fungl/tools/fungl.rb

The MIT License (MIT)

Copyright (c) 2022 George Watson

Permission is hereby granted, free of charge, to any person
obtaining a copy of this software and associated documentation
files (the "Software"), to deal in the Software without restriction,
including without limitation the rights to use, copy, modify, merge,
publish, distribute, sublicense, and/or sell copies of the Software,
and to permit persons to whom the Software is furnished to do so,
subject to the following conditions:

The above copyright notice and this permission notice shall be
included in all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY
CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT,
TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE
SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE. */

#include "fungl.h"
HEADER

def importSource(path)
    skip = true
    File.readlines(path).each do |line|
        if skip
            skip = false if line =~ /^#include "\S+.h"/
        else
            puts line
        end
    end
end

importSource("src/glLoader.c")
importSource("src/glWindow.c")
