/* cwcgl.h -- single public entry point for cwcGL.
 *
 * Users of the library (test dylibs, hosts) should include this instead of
 * loader.h/registry.h/reload.h directly. This file is hand-written and not
 * regenerated by gl.rb -- it just bundles the three components in the
 * order they depend on each other:
 *
 *   loader.h   generated OpenGL 3.3 core bindings + cwcgl_InitOpenGL()
 *   registry.h GL object lifecycle tracking, built on top of loader.h
 *   reload.h   generic dylib hot-reload core (no GL knowledge of its own)
 *
 * A dylib built against client.c only needs loader.h for the __glFoo
 * declarations and cwcglLoadAPI -- registry.h and reload.h are host-only,
 * but including them from a child dylib is harmless (they declare
 * functions, they don't require linking against reload.c/registry.c
 * unless something actually calls them).

 The MIT License (MIT)

 Copyright (c) 2022 George Watson

 Permission is hereby granted, free of charge, to any person
 obtaining a copy of this software and associated documentation
 files (the "Software"), to deal in the Software without restriction,
 including without limitation the rights to use, copy, modify, merge,
 publish, distribute, sublicense, and/or sell copies of the Software,
 and to permit persons to whom the Software is furnished to do so,
 subject to the following conditions:

 The above copyright notice and this permission notice shall be
 included in all copies or substantial portions of the Software.

 THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
 EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
 MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
 IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY
 CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT,
 TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE
 SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
*/

#ifndef CWCGL_H
#define CWCGL_H
#if defined(__cplusplus)
extern "C" {
#endif

#include "loader.h"
#include "registry.h"
#include "reload.h"

#if defined(__cplusplus)
}
#endif
#endif // CWCGL_H
